# Generated by Django 5.2.17 on 2026-09-05 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('bullets', models.TextField(help_text='One bullet per line.', verbose_name='Bullet list')),
                ('image', models.ImageField(blank=True, help_text='Square-ish photos work best. If you leave this empty, a placeholder is used.', upload_to='capabilities/', verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Home page card',
                'verbose_name_plural': 'Home page cards (Design / Build / Service)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('scope', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Contact form inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('title', models.CharField(max_length=80, verbose_name='Job title')),
                ('location', models.CharField(default='Chicago, IL', max_length=80, verbose_name='Location')),
                ('job_type', models.CharField(default='Full-time', help_text='Example: Full-time, Apprenticeship', max_length=40, verbose_name='Type')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this job without deleting it.', verbose_name='Show on the website')),
            ],
            options={
                'verbose_name': 'Job opening',
                'verbose_name_plural': 'Job openings',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('text', models.CharField(max_length=80, verbose_name='Line of text')),
            ],
            options={
                'verbose_name': 'Marquee line',
                'verbose_name_plural': 'Marquee lines (footer ticker)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('title', models.CharField(max_length=160, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank and it will be filled in from the title.', unique=True, verbose_name='URL name')),
                ('excerpt', models.CharField(blank=True, help_text='One sentence for the list page.', max_length=280, verbose_name='Short excerpt')),
                ('body', models.TextField(help_text='Separate paragraphs with a blank line.', verbose_name='Body')),
                ('cover_image', models.ImageField(blank=True, upload_to='posts/', verbose_name='Cover photo')),
                ('is_published', models.BooleanField(default=False, verbose_name='Show on the website')),
                ('published_at', models.DateField(blank=True, help_text="Shown on the post. Leave blank if you don't care.", null=True, verbose_name='Publish date')),
            ],
            options={
                'verbose_name': 'Journal post',
                'verbose_name_plural': 'Journal posts',
                'ordering': ['-published_at', 'order', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('client', models.CharField(help_text='You can keep this anonymous. Example: REGIONAL FOOD PROCESSOR', max_length=80, verbose_name='Client (as shown)')),
                ('title', models.CharField(max_length=120, verbose_name='Project title')),
                ('slug', models.SlugField(blank=True, help_text='Leave blank and it will be filled in from the title.', unique=True, verbose_name='URL name')),
                ('year', models.CharField(blank=True, max_length=8, verbose_name='Year')),
                ('scope', models.CharField(blank=True, help_text='Example: LOW VOLTAGE, FIBER OPTICS', max_length=40, verbose_name='Scope tag')),
                ('blurb', models.TextField(help_text='One or two sentences. Used on the projects list.', verbose_name='Short summary')),
                ('body', models.TextField(blank=True, help_text='Optional longer story for the project page. Separate paragraphs with a blank line.', verbose_name='Full write-up')),
                ('cover_image', models.ImageField(blank=True, upload_to='projects/', verbose_name='Cover photo')),
                ('is_published', models.BooleanField(default=True, verbose_name='Show on the website')),
                ('is_featured', models.BooleanField(default=False, help_text='Unused for now — reserved if you want a featured strip later.', verbose_name='Feature on the home page')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('tag', models.CharField(help_text='Shown in caps next to the number. Example: DESIGN', max_length=20, verbose_name='Small label')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('copy', models.TextField(verbose_name='Description')),
                ('bullets', models.TextField(help_text='One bullet per line.', verbose_name='Bullet list')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services (the three big ones)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Black Shell Technology', max_length=80, verbose_name='Company name')),
                ('phone', models.CharField(default='+1 (555) 555-0142', help_text='Shown on the contact page. Example: +1 (312) 555-0142', max_length=40, verbose_name='Phone number')),
                ('email', models.EmailField(default='projects@blackshell.tech', help_text='The address visitors see. Inquiries also go here unless you change the server setting.', max_length=254, verbose_name='Public email')),
                ('founded_year', models.CharField(default='2018', max_length=8, verbose_name='Founded year')),
                ('licensed_states', models.CharField(default='IL · IN · WI', help_text='Shown on the About page. Example: IL · IN · WI', max_length=40, verbose_name='Licensed states')),
                ('license_label', models.CharField(default='CHICAGO EC', help_text='Short label above the license number.', max_length=40, verbose_name='License label')),
                ('license_number', models.CharField(default='#SE-014277', max_length=40, verbose_name='License number')),
                ('city', models.CharField(default='Chicago, IL', max_length=80, verbose_name='City line')),
                ('service_area', models.CharField(default='Chicago, IL — serving Chicagoland & the greater IL · IN · WI region', max_length=160, verbose_name='Service area')),
                ('side_rail', models.CharField(default='DESIGN  •  BUILD  •  SERVICE', help_text='The vertical text on large screens.', max_length=80, verbose_name='Left-edge rail text')),
                ('hero_headline', models.TextField(default="INFRASTRUCTURE\nFOR WHAT'S NEXT.", help_text='One line per row. It will break exactly where you press Enter.', verbose_name='Home headline')),
                ('hero_tagline', models.TextField(default='A full-service electrical and technology contractor serving retail, commercial, and industrial clients across Chicagoland.', verbose_name='Home tagline')),
                ('hero_body', models.TextField(default='We hold safety, sustainability, and precision at the center of every project we deliver.', verbose_name='Home supporting line')),
                ('hero_caption_1', models.CharField(default='BLACK SHELL TECHNOLOGY', max_length=80, verbose_name='Spiral caption — line 1')),
                ('hero_caption_2', models.CharField(default='DESIGN · BUILD · SERVICE', max_length=80, verbose_name='Spiral caption — line 2')),
                ('hero_caption_3', models.CharField(default='DELIVERING WORK YOU CAN COUNT ON', max_length=80, verbose_name='Spiral caption — line 3')),
                ('capabilities_label', models.CharField(default='ENGAGEMENT', max_length=40, verbose_name='Home cards label')),
                ('about_eyebrow', models.CharField(default='ABOUT', max_length=40, verbose_name='About label')),
                ('about_headline', models.TextField(default='BUILT ON\nDISCIPLINE.', help_text='One line per row.', verbose_name='About headline')),
                ('about_p1', models.TextField(default='Founded in 2018, Black Shell Technology is a woman-owned, full-service electrical and technology contractor rooted in the Chicago area, serving retail, commercial, and industrial clients.', verbose_name='About — paragraph 1')),
                ('about_p2', models.TextField(default='We work where downtime is not an option. Multi-site retail rollouts. Commercial build-outs. Distribution centers and manufacturing floors. Our crews carry the certifications and craft discipline these environments require.', verbose_name='About — paragraph 2')),
                ('about_p3', models.TextField(default='We are committed to a single principle: every project deserves the same craft discipline, regardless of scale. Our team was founded by veterans of the electrical and fiber trades, and that conviction shapes every decision we make.', verbose_name='About — paragraph 3')),
                ('services_eyebrow', models.CharField(default='SERVICES', max_length=40, verbose_name='Services label')),
                ('services_headline', models.CharField(default='WHAT WE DELIVER.', max_length=80, verbose_name='Services headline')),
                ('services_intro', models.TextField(default='Forward-thinking electrical and technology solutions that bridge advanced engineering with flawless execution. From renewable energy systems to intelligent building infrastructure — delivered on time, on budget, and to the highest standards of safety and sustainability.', verbose_name='Services intro')),
                ('tech_eyebrow', models.CharField(default='TECH SOLUTIONS', max_length=40, verbose_name='Tech list label')),
                ('tech_headline', models.CharField(default='DYNAMIC & CUSTOMIZED TECH.', max_length=80, verbose_name='Tech list headline')),
                ('tech_intro', models.TextField(default="A robust suite of services designed to ensure your technology infrastructure doesn't just get by — it thrives. Working directly with your team, we design and implement tailor-made strategies that are seamlessly integrated, highly efficient, and built to scale.", verbose_name='Tech list intro')),
                ('projects_eyebrow', models.CharField(default='PROJECTS', max_length=40, verbose_name='Projects label')),
                ('projects_headline', models.CharField(default='WORK YOU CAN COUNT ON.', max_length=80, verbose_name='Projects headline')),
                ('projects_intro', models.TextField(default='A sample of recent electrical and technology work across Chicagoland — retail rollouts, commercial build-outs, and the infrastructure that keeps operations running.', verbose_name='Projects intro')),
                ('careers_eyebrow', models.CharField(default='CAREERS', max_length=40, verbose_name='Careers label')),
                ('careers_headline', models.CharField(default='JOIN THE CREW.', max_length=80, verbose_name='Careers headline')),
                ('careers_intro', models.TextField(default="We back our team — competitive pay, full benefits, room to grow your craft, and the kind of projects you'll tell stories about for the rest of your career.", verbose_name='Careers intro')),
                ('careers_footer', models.TextField(default="Don't see the right role? Reach out anyway — we're always interested in connecting with skilled trades-people who care about their craft.", verbose_name='Careers closing line')),
                ('journal_eyebrow', models.CharField(default='JOURNAL', max_length=40, verbose_name='Journal label')),
                ('journal_headline', models.CharField(default='FROM THE FIELD.', max_length=80, verbose_name='Journal headline')),
                ('journal_intro', models.TextField(default='Notes, project stories, and the occasional dispatch from the shop.', verbose_name='Journal intro')),
                ('contact_eyebrow', models.CharField(default='CONTACT', max_length=40, verbose_name='Contact label')),
                ('contact_headline', models.TextField(default='START\nYOUR\nPROJECT.', help_text='One line per row.', verbose_name='Contact headline')),
                ('contact_intro', models.TextField(default='Tell us about the project. We respond within one business day — often sooner.', verbose_name='Contact intro')),
                ('contact_success', models.CharField(default='MESSAGE RECEIVED.', max_length=80, verbose_name='Thank-you message')),
                ('contact_success_body', models.CharField(default='A member of our team will be in touch within one business day.', max_length=160, verbose_name='Thank-you supporting line')),
                ('meta_title', models.CharField(default='Black Shell Technology — Retail, Commercial & Industrial Electrical Contractor · Chicago', max_length=120, verbose_name='Browser tab title')),
                ('meta_description', models.TextField(default='A woman-owned, full-service electrical and technology contractor serving retail, commercial, and industrial clients across the Chicago area. We hold safety, sustainability, and precision at the center of every project we deliver.', verbose_name='Search-engine description')),
            ],
            options={
                'verbose_name': 'Site text',
                'verbose_name_plural': 'Site text',
            },
        ),
        migrations.CreateModel(
            name='TechService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Tech service',
                'verbose_name_plural': 'Tech services (the long list)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('label', models.CharField(help_text='Example: 01 / DISCIPLINE', max_length=40, verbose_name='Small label')),
                ('title', models.CharField(max_length=80, verbose_name='Title')),
                ('copy', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'About value',
                'verbose_name_plural': 'About values (the three columns)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('image', models.ImageField(upload_to='posts/gallery/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='Caption')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.post')),
            ],
            options={
                'verbose_name': 'Post photo',
                'verbose_name_plural': 'Post photos',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.', verbose_name='Order')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=160, verbose_name='Caption')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pages.project')),
            ],
            options={
                'verbose_name': 'Project photo',
                'verbose_name_plural': 'Project photos',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
